# Generated by Django 2.2.3 on 2019-07-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_date',), 'verbose_name': 'Post'},
        ),
    ]
